### PR TITLE
Add basic drivetrain support

### PR DESCRIPTION
**Pull request by P1n3appl3**
Also adds code for the NAVX gyroscope

### CODE REVIEW

**Comment by CheezBallzPi** [comment]
This change is [Reviewable](https://reviewable.io/reviews/roboeagles4828/2017robot/12)

**Comment by CheezBallzPi** [comment]
Will take a look after hw 😛

**Comment by P1n3appl3** [comment]
why am i not allowed to merge my own freakin branch

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12#-:-KaolrDd1vgdfYYAUYyz:b-c91c36)*

**Comment by CheezBallzPi** [comment]
I made it so you can't do that. Prevents people adding crap and everyone else like "Wait wtf is this"

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12#-:-Kaom46vrtK0hgq-W2dI:blsaj1d)*

**Comment by CheezBallzPi** [comment]
And don't you DARE review it yourself.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12#-:-KaomCe2I_h6gpl_1zUm:b-pm5hin)*

**Comment by P1n3appl3** [comment]
Did you not totally review the last like 4 PR's yourself tho :P

**Comment by CheezBallzPi** [comment]
BEFORE I added this 😛

**Comment by P1n3appl3** [comment]
We can just use Githubs built in code review so we dont have to go to reviewable u know

**Comment by P1n3appl3** [comment]
It just seems to bloat the process and make me open more tabs

**Comment by CheezBallzPi** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/org/usfirst/frc/team4828/DriveTrain.java, line 50 at r1](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12#-Kaommo5g3M8OBaa-rDf:-Kaommo5g3M8OBaa-rDg:b-wwpkfe) ([raw file](https://github.com/roboeagles4828/2017robot/blob/82029f5aebb497b9dd4432dc60446d9446693281/src/main/java/org/usfirst/frc/team4828/DriveTrain.java#L50)):*
> ```Java
>     public void mecanumDrive(double x, double y, double rotation, double gyroAngle) {
>         // Negate y for the joystick.
>         y = -y;
> ```

What's this for? I don't have much bg info on mecanums...

---

*[src/main/java/org/usfirst/frc/team4828/Robot.java, line 26 at r1](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12#-KaomzqFhbez8t6zANZl:-KaomzqFhbez8t6zANZm:b21szku) ([raw file](https://github.com/roboeagles4828/2017robot/blob/82029f5aebb497b9dd4432dc60446d9446693281/src/main/java/org/usfirst/frc/team4828/Robot.java#L26)):*
> ```Java
>     public void autonomousInit() {
>         super.autonomousInit();
>         System.out.println("Entering auton...");
> ```

TECHNICALLY not entering auton yet, that's in periodic, but that's just my perfectionist showing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12)*

**Comment by P1n3appl3** [comment]
*[src/main/java/org/usfirst/frc/team4828/DriveTrain.java, line 50 at r1](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12#-Kaommo5g3M8OBaa-rDf:-KaonVyqeHIKpYJMPZGD:b-gzad9j) ([raw file](https://github.com/roboeagles4828/2017robot/blob/82029f5aebb497b9dd4432dc60446d9446693281/src/main/java/org/usfirst/frc/team4828/DriveTrain.java#L50)):*
<details><summary><i>Previously, CheezBallzPi (Jackie Chen) wrote…</i></summary><blockquote>

What's this for? I don't have much bg info on mecanums...
</blockquote></details>

it's copied from wpilib, i can explain the math to u later if u want, also we can write unit tests for the supporting math functions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12)*

**Comment by CheezBallzPi** [comment]
I'm gonna try both probs this week or next

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12#-:-KaonkL-GXfybTB20dqr:b25nknb)*

**Comment by CheezBallzPi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12#-:-Kaonyk4Ij5iuK9SZCbP:bg7igk9)*

**Comment by P1n3appl3** [comment]
*[src/main/java/org/usfirst/frc/team4828/Robot.java, line 26 at r1](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12#-KaomzqFhbez8t6zANZl:-KaonuAFqNOJt1Y2w0FM:b-ap0thj) ([raw file](https://github.com/roboeagles4828/2017robot/blob/82029f5aebb497b9dd4432dc60446d9446693281/src/main/java/org/usfirst/frc/team4828/Robot.java#L26)):*
<details><summary><i>Previously, CheezBallzPi (Jackie Chen) wrote…</i></summary><blockquote>

TECHNICALLY not entering auton yet, that's in periodic, but that's just my perfectionist showing.
</blockquote></details>

Wait what, it enters auton at the beginning of auton init right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12)*

**Comment by CheezBallzPi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/org/usfirst/frc/team4828/Robot.java, line 26 at r1](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12#-KaomzqFhbez8t6zANZl:-Kaoo2TEZ_bzJI1nUnHh:bsc5k4e) ([raw file](https://github.com/roboeagles4828/2017robot/blob/82029f5aebb497b9dd4432dc60446d9446693281/src/main/java/org/usfirst/frc/team4828/Robot.java#L26)):*
<details><summary><i>Previously, P1n3appl3 (Joseph Ryan) wrote…</i></summary><blockquote>

Wait what, it enters auton at the beginning of auton init right?
</blockquote></details>

It gets ready for auton, but the actual AUTON is in periodic. I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12)*

**Comment by CheezBallzPi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/org/usfirst/frc/team4828/Robot.java, line 26 at r1](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12#-KaomzqFhbez8t6zANZl:-KaooBmOYoacVuJNhLmo:b2nhksp) ([raw file](https://github.com/roboeagles4828/2017robot/blob/82029f5aebb497b9dd4432dc60446d9446693281/src/main/java/org/usfirst/frc/team4828/Robot.java#L26)):*
<details><summary><i>Previously, CheezBallzPi (Jackie Chen) wrote…</i></summary><blockquote>

It gets ready for auton, but the actual AUTON is in periodic. I think.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12)*

**Comment by CheezBallzPi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/org/usfirst/frc/team4828/Robot.java, line 26 at r1](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12#-KaomzqFhbez8t6zANZl:-KaooEAuOXFDvHHepNXe:bb6ywmx) ([raw file](https://github.com/roboeagles4828/2017robot/blob/82029f5aebb497b9dd4432dc60446d9446693281/src/main/java/org/usfirst/frc/team4828/Robot.java#L26)):*
<details><summary><i>Previously, CheezBallzPi (Jackie Chen) wrote…</i></summary><blockquote>

OK
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12)*

**Comment by CheezBallzPi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/org/usfirst/frc/team4828/Robot.java, line 26 at r1](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12#-KaomzqFhbez8t6zANZl:-KaooLPEVuLgEbzupiXY:b4wa5z5) ([raw file](https://github.com/roboeagles4828/2017robot/blob/82029f5aebb497b9dd4432dc60446d9446693281/src/main/java/org/usfirst/frc/team4828/Robot.java#L26)):*
<details><summary><i>Previously, CheezBallzPi (Jackie Chen) wrote…</i></summary><blockquote>

LGTM
</blockquote></details>

pls end...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12)*

**Comment by P1n3appl3** [comment]
*[src/main/java/org/usfirst/frc/team4828/Robot.java, line 26 at r1](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12#-KaomzqFhbez8t6zANZl:-KaooPlIn8e0-ZopoiNC:bmx34at) ([raw file](https://github.com/roboeagles4828/2017robot/blob/82029f5aebb497b9dd4432dc60446d9446693281/src/main/java/org/usfirst/frc/team4828/Robot.java#L26)):*
<details><summary><i>Previously, CheezBallzPi (Jackie Chen) wrote…</i></summary><blockquote>

pls end...
</blockquote></details>

This is why we should use githubs instead i keep having to open this crap

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/roboeagles4828/2017robot/12)*

**Comment by alebcay** [comment]
*Please* switch to the default GitHub built-in review system. It produces so much less bloat in the comments of the PR.

**Comment by CheezBallzPi** [comment]
@alebcay I've already killed Reviewable. We are on the path to unbloatedness.

**Pull request merged**
